### ISSUE TITLE
Replace setup.py with pyproject.toml

### ISSUE THREAD

**Issue by mbkumar** [alejandrojuria/tightbinder#6]
@alejandrojuria 

I am one of the reviewers for your JOSS paper. I'll open separate issues for each of the comments that I want to be addressed.

setup.py is deprecated and the new installation approach uses pyproject.toml. Your installation is simple enough that conversion shouldn't take much time after you understand the new build framework. Please replace setup.py with pyproject.toml.

**Comment by alejandrojuria** [comment]
Hello @mbkumar, thank you for taking your time reviewing the code. 

I have already updated the installation procedure, and removed setup.py in favour of pyproject.toml. I believe the configuration file is working properly.

**Comment by mbkumar** [comment]
Thanks
