### ISSUE TITLE
Add dependencies to installation

### ISSUE THREAD

**Issue by mbkumar** [alejandrojuria/tightbinder#7]
I don't have to install the dependencies such as numpy, scipy, and matplotlib separately. You can specify them within the setup.py or pyproject.toml, so they are installed automatically along with tightbinder. 

After #6 is addressed, please specify the dependencies within the pyproject.toml

**Comment by alejandrojuria** [comment]
I have moved all the dependencies to the pyproject.toml file, and removed the requirements.txt file. If you think it is okay, we can close this issue and also the previous one regarding the file itself.
